
CREATE VIEW [MonthsOfYear]
AS
SELECT CAST(1 AS TINYINT) AS [Ordinal], 'January' AS [Name]
UNION SELECT CAST(2 AS TINYINT), 'February'
UNION SELECT CAST(3 AS TINYINT), 'March'
UNION SELECT CAST(4 AS TINYINT), 'April' 
UNION SELECT CAST(5 AS TINYINT), 'May'
UNION SELECT CAST(6 AS TINYINT), 'June' 
UNION SELECT CAST(7 AS TINYINT), 'July' 
UNION SELECT CAST(8 AS TINYINT), 'August' 
UNION SELECT CAST(9 AS TINYINT), 'September' 
UNION SELECT CAST(10 AS TINYINT), 'October'
UNION SELECT CAST(11 AS TINYINT), 'November' 
UNION SELECT CAST(12 AS TINYINT), 'December'
