
CREATE VIEW [Years]
AS
SELECT d.[Number]+u.[Number] AS [Number], CAST(d.[Number]+u.[Number] AS VARCHAR) AS [Slug]
FROM [Decades] d
CROSS JOIN (
	SELECT CAST(0 AS TINYINT) AS [Number]
	UNION SELECT CAST(1 AS TINYINT) 
	UNION SELECT CAST(2 AS TINYINT) 
	UNION SELECT CAST(3 AS TINYINT) 
	UNION SELECT CAST(4 AS TINYINT) 
	UNION SELECT CAST(5 AS TINYINT) 
	UNION SELECT CAST(6 AS TINYINT) 
	UNION SELECT CAST(7 AS TINYINT) 
	UNION SELECT CAST(8 AS TINYINT) 
	UNION SELECT CAST(9 AS TINYINT) 
) u
